#!/usr/bin/env sh

### BEGIN INIT INFO
# Provides:          cert-sync
# Required-Start:    mysql
# Required-Stop:     mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SSL cert synchronization daemon
### END INIT INFO

. /lib/lsb/init-functions

SCRIPT=/srv/cert/scripts/syncd.php
USER=cert-sync
PIDFILE=/var/run/cert-sync.pid

test -f $SCRIPT || exit 0

case "$1" in
start)
	log_daemon_msg "Starting cert-sync daemon"
	start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $SCRIPT --user $USER --
	log_end_msg $?
	;;
stop)
	log_daemon_msg "Stopping cert-sync daemon"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --name syncd.php --user $USER
	log_end_msg $?
	rm -f $PIDFILE
	;;
restart)
	$0 stop && $0 start
	;;
*)
	log_action_msg "Usage: /etc/init.d/cert-sync {start|stop|restart}"
	exit 2
	;;
esac
exit 0
